public/styles/layout.css
views/pages/contact.ejs

As part of the copy changes I updated the layout of the messages on the contact page to stack vertically as to accommodate the text a little better. 
Most of the CSS changes below are just re-formatting.

Update copy to reflect resource guides are out of stock

---

package-lock.json
package.json
public/styles/base.css
public/styles/layout.css

This reformats the results into a columnar layout so that all of the items are the screen (instead of being cut off like they were previously). Unfortunately, this is still a bit ugly, but at least it's usable now.

View cut off fix

---

public/styles/layout.css

Labels now line up correctly when you search after logging in.

fixed label alignment on search when logged in

---

server.js

Quick fix for errors caused with apostrophes.

added regex to replace apostrophes causing SQL errors

---

views/pages/auth/search-admin.ejs

Added "checked" attribute to input.

set 'includes' to default for search

---

views/pages/detail.ejs

Added regular expression to detect if URI starts with "http://" or "https://", and if not, prepend with "http://".

Web address fix

---

public/styles/base.css
views/layout/footer.ejs
views/layout/header.ejs
views/pages/contact.ejs

Moved login link to footer and styled to make it similar to the one on Real Change's site. Updated info re: 4th edition in contact page. External links in top nav open in new tab (as requested).

moved login link, updated contact page

---

views/pages/auth/edit-details.ejs

Updated script to say "fourth edition" and added a couple of sentences about COVID restrictions.

added script changes (fourth edition, COVID restrictions)

---

package-lock.json
package.json

This preinstall script is not being used.

this file is not necessary, and it's causing errors on installation

---

db/migrations/20200426183951_create_organization_table.js

Adding the tempcovid column to knex script.

added tempcovid column

---

views/pages/detail.ejs

removed duplicate 'last-content' ID from organization-items

---

public/styles/base.css
views/pages/contact.ejs

Uncommented code for order form, updated text for ordering fourth edition, minor HTML and CSS adjustments.

Fourth edition

---

views/pages/auth/copy-requests.ejs

Changed from number of copies ordered to number of copies remaining.

change to number of copies available

---

views/pages/confirmation.ejs

updated hours and phone number

---

server.js
views/pages/auth/copy-requests.ejs

Get accurate total of copies remaining through second SQL query.

Copy requests total

---

server.js
views/pages/auth/copy-requests.ejs

Reverting download button and associated functionality which caused sign in issues

Download orders

---

public/styles/layout.css
views/pages/confirmation.ejs
views/pages/contact.ejs

Updated text per request from Ari. Having multiple instances of an ID on the same page is not valid HTML, so I changed them to classes.

added new text + changed id to class

---

db/migrations/20200426184237_create_requests_table.js
server.js

New datetime column for requests table so that we know when requests were made.

Date field

---

server.js
views/pages/dropdown.ejs

Search page showed all categories, including inactive categories. Rewrote search query so easier to understand and added check that category was currently active.

adding organization_x_category.active=true check to search query

---

.github/workflows/tests.yml
server.js
test/test.js

This fixes a couple issues with the unit tests at `test/test.js`:
1. Assertions were out-of-date for the tests for `makeGenderQuery()` and `makeSQL()`, so I updated them. These tests should be refactored IMO so they're easier to read, but I figured it was better to get them passing first
2. Tests hang at the end. This is because it's importing `server.js`, which starts up a server and establishes a PG connection, which weren't being closed. I added code to terminate both at the end of the tests.
To avoid the tests from getting out-of-date in the future, I also adding a Github Action to automatically run the tests for every commit.

Fix tests and add Github Action to automatically run on all commits

---

docker-compose.yml
fly.toml
package.json
preinstall.js
server.js
test/test.js

Details at
https://docs.google.com/document/d/1XpxEMcmUJOFFbzIdfDomUa64ds4RQ_ZAYc52ySyHgiM/edit?usp=sharing
Changes:
1. Add fly.toml with deployment configuration
2. Remove unnecessary `GOOGLE_APPLICATION_CREDENTIALS` variable to simplify secret management
3. Update server.js to use a connection pool for connecting to PostgreSQL, since that facilitates automatic reconnects. This is necessary because Fly.io seems to automatically close connections after ~1 hour.

Migration from Heroku to Fly.io

---

public/styles/layout.css
server.js
views/pages/auth/mailing-list.ejs
views/pages/auth/sidebar.ejs

This is so Tye doesn't have to ask a developer to dump the contents of `mailing_list`

Add basic admin page for mailing list

---

db/seeds/data/category.csv
views/pages/auth/addnew-detail.ejs
views/pages/auth/edit-details.ejs
views/pages/index.ejs

Also removed the indices from each `name="category[xx]" attribute, since they're unnecessary (see
https://www.npmjs.com/package/qs#user-content-parsing-arrays)

Add "Disability services" category

---

db/migrations/20230630234254_add_is_branch_to_requests.js
server.js
views/pages/contact.ejs

Update contact page for 6th edition orders

---

views/pages/contact.ejs

Commented out the form and made the mailing list form active.

change to mailing list form
